### ISSUE TITLE
nRF52840 usb dongle as receiver?

### ISSUE THREAD

**Issue by pashky** [joric/jorian#2]
Hi

Just dived into rabbit hole of wireless split boards and now of course I want one. I’ve been using wired ergodash clone for some time and I like it, but your design looks particularly appealing because of Ъ and creative use of 100x100mm :)

I have a question though. Now that nRF52 branch of QMK exists, is there anything that would not let me use this thing as receiver? Any thoughts?

https://www.digikey.co.uk/product-detail/en/nordic-semiconductor-asa/NRF52840-DONGLE/1490-1073-ND/9491124

**Comment by joric** [comment]
You can try. I just used nRF51 soldered to the 3.3v pro micro. https://github.com/reversebias/mitosis/pull/10
Also read wiki https://github.com/joric/jorian/wiki/Issues you may not like it so much there's no LED power switching and nRF51 in general is pretty much obsolete.

**Comment by pashky** [comment]
Thanks. Didn’t notice that issues page before. Nrf51 is still cheaper and I don’t  plan to install LEDs anyway, so as long as it works I figured I’d give it a go. 

I’m interested in your opinion though, what would you use if you’re to build something similar today?

**Comment by joric** [comment]
I have a few modules used here https://github.com/joric/nrfmicro/ I'd probably use them but I don't know I'd prefer hotswap pro-micro based keyboards to dead-soldered ones.

There's a dead-soldered closed-source keyboard like this already (runs QMK nrf52 branch), SISO59 by Sekigon https://github.com/sekigon-gonnoc/SISO59-doc/blob/master/README.md

I was also trying to layout USB-C in the [usb-version](https://github.com/joric/jorian/tree/usb-version) branch (unfinished), I think it's possible. Sadly nRF51 doesn't have hardware USB and I haven't tried running V-USB on it (there's no memory space for that).
